name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Print working directory
      run: pwd

    - name: List files in the root directory
      run: ls -la

    - name: List files in the project directory
      working-directory: nextjs-fastapi-framework-main
      run: ls -la

    - name: Build the Docker image
      working-directory: nextjs-fastapi-framework-main
      run: docker build . --file Dockerfile --tag my-image-name:latest

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Tag Docker image for ACR
      run: docker tag my-image-name:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-image-name:latest

    - name: Push Docker image to ACR
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-image-name:latest
